steps:

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'chmod +x ./host.sh'

# Optionnel : spécifiez les substitutions, images, etc.
timeout: '120s'